In [14]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

#entramos a la carpeta:

In [15]:
import os
# Entramos en la carpeta del proyecto donde se encuentran los datasets
os.chdir('/content/drive/MyDrive/EDA')

#Cargamos los archivos!

In [16]:
# Cargamos las lecturas meteorológicas y la información de las estaciones
import pandas as pd

lecturas = pd.read_json("aruba_readings_20260924.json")
estaciones = pd.read_json("aruba_stations.json")

#Primeras filas

In [17]:
lecturas.head()

,id,station_id,timestamp,temperature_c,humidity_pct,wind_speed_kmh,wind_direction_deg,pressure_hpa,precipitation_mm,visibility_km,uv_index
0,ccdcf0e5-6ca1-4d82-bc25-0881de96dc7c,09ea9cd3-4d28-4049-9dfb-3c5bd5849e9c,2025-09-01 00:00:00+00:00,32.4,68.9,23.1,45.7,1013.2,0.0,11.8,0.0
1,c1a1b04e-61c2-43f6-b478-70f9aa765c5b,4ca4c103-894d-4f59-a911-f3abb8077e3c,2025-09-01 00:00:00+00:00,31.9,68.8,22.2,41.6,1013.1,0.0,11.5,0.0
2,e89069bc-40ed-48c1-ad94-b0bb9c7dd556,5c5c4158-91cb-4073-ab4c-9bb10037dc16,2025-09-01 00:00:00+00:00,31.8,68.1,23.4,40.0,1013.0,0.0,11.3,0.0
3,509121ee-dc99-4a22-b77c-2a88a644753f,82a31d3a-9895-42e5-8ea0-11e8cb15b964,2025-09-01 00:00:00+00:00,31.3,68.9,21.3,47.3,1013.2,0.0,11.7,0.0
4,05b70544-1f18-4a3e-993a-b82b453bc12e,8f0185fa-a4c3-41c1-8f3b-d08f4f6aece0,2025-09-01 00:00:00+00:00,32.4,67.2,22.8,50.7,1013.1,0.0,12.0,0.0

#Exploración inicial de los datos
Visualizamos las primeras filas de ambos datasets para comprobar su estructura, columnas y tipos de información disponibles.

In [18]:
estaciones.head()

,id,name,code,latitude,longitude,elevation_m,district,is_active
0,4ca4c103-894d-4f59-a911-f3abb8077e3c,Alto Vista,WS-ALT-11,12.5912,-70.0374,25,Noord,True
1,de2ee07b-de63-49db-a669-64177a688bbf,Queen Beatrix Airport,WS-APT-02,12.5042,-70.0031,18,Oranjestad,True
2,acb2fa5c-518a-4a38-b68d-bf8e3b041ccf,Arikok National Park,WS-ARK-10,12.5009,-69.9538,120,Santa Cruz,True
3,f678bd98-07d3-459d-bd4d-7aaba7051847,Hooiberg Summit,WS-HOO-07,12.5204,-69.9992,165,Santa Cruz,True
4,8f0185fa-a4c3-41c1-8f3b-d08f4f6aece0,Malmok,WS-MAL-12,12.5961,-70.0489,6,Noord,True

In [19]:
print(lecturas.columns)
print(estaciones.columns)

Index(['id', 'station_id', 'timestamp', 'temperature_c', 'humidity_pct',
       'wind_speed_kmh', 'wind_direction_deg', 'pressure_hpa',
       'precipitation_mm', 'visibility_km', 'uv_index'],
      dtype='object')
Index(['id', 'name', 'code', 'latitude', 'longitude', 'elevation_m',
       'district', 'is_active'],
      dtype='object')

#Relacionamos

In [20]:
# Relacionamos cada lectura meteorológica con su estación.
# station_id de las lecturas corresponde con id de aruba_stations.json.

datos = lecturas.merge(
    estaciones,
    left_on="station_id",
    right_on="id",
    how="left"
)

In [21]:
datos.head()

,id_x,station_id,timestamp,temperature_c,humidity_pct,wind_speed_kmh,wind_direction_deg,pressure_hpa,precipitation_mm,visibility_km,uv_index,id_y,name,code,latitude,longitude,elevation_m,district,is_active
0,ccdcf0e5-6ca1-4d82-bc25-0881de96dc7c,09ea9cd3-4d28-4049-9dfb-3c5bd5849e9c,2025-09-01 00:00:00+00:00,32.4,68.9,23.1,45.7,1013.2,0.0,11.8,0.0,09ea9cd3-4d28-4049-9dfb-3c5bd5849e9c,Noord,WS-NRD-03,12.5645,-70.0319,15,Noord,True
1,c1a1b04e-61c2-43f6-b478-70f9aa765c5b,4ca4c103-894d-4f59-a911-f3abb8077e3c,2025-09-01 00:00:00+00:00,31.9,68.8,22.2,41.6,1013.1,0.0,11.5,0.0,4ca4c103-894d-4f59-a911-f3abb8077e3c,Alto Vista,WS-ALT-11,12.5912,-70.0374,25,Noord,True
2,e89069bc-40ed-48c1-ad94-b0bb9c7dd556,5c5c4158-91cb-4073-ab4c-9bb10037dc16,2025-09-01 00:00:00+00:00,31.8,68.1,23.4,40.0,1013.0,0.0,11.3,0.0,5c5c4158-91cb-4073-ab4c-9bb10037dc16,Paradera,WS-PAR-06,12.5354,-70.0050,30,Paradera,True
3,509121ee-dc99-4a22-b77c-2a88a644753f,82a31d3a-9895-42e5-8ea0-11e8cb15b964,2025-09-01 00:00:00+00:00,31.3,68.9,21.3,47.3,1013.2,0.0,11.7,0.0,82a31d3a-9895-42e5-8ea0-11e8cb15b964,Savaneta,WS-SAV-08,12.4526,-69.9497,4,Savaneta,True
4,05b70544-1f18-4a3e-993a-b82b453bc12e,8f0185fa-a4c3-41c1-8f3b-d08f4f6aece0,2025-09-01 00:00:00+00:00,32.4,67.2,22.8,50.7,1013.1,0.0,12.0,0.0,8f0185fa-a4c3-41c1-8f3b-d08f4f6aece0,Malmok,WS-MAL-12,12.5961,-70.0489,6,Noord,True

#Validación de la relación entre lecturas y estaciones

In [22]:
print("Lecturas:", len(lecturas))
print("Estaciones:", len(estaciones))
print("Datos unidos:", len(datos))

print("Lecturas sin estación:", datos["name"].isna().sum())

Lecturas: 1351008
Estaciones: 12
Datos unidos: 1351008
Lecturas sin estación: 0

In [23]:
print("Estaciones distintas en lecturas:",
      lecturas["station_id"].nunique())

print("Estaciones disponibles:",
      estaciones["id"].nunique())

Estaciones distintas en lecturas: 12
Estaciones disponibles: 12

In [24]:
print(
    "IDs duplicados en estaciones:",
    estaciones["id"].duplicated().sum()
)

IDs duplicados en estaciones: 0

## RF-01 — Ingesta de datos de estaciones

Se cargaron los ficheros `train_aruba_lecturas.json` y
`aruba_stations.json`.

Se relacionaron las lecturas con las estaciones mediante
`station_id`.

Resultados:
- Lecturas cargadas: 1.351.008
- Estaciones: 12
- Lecturas después de la unión: 1.351.008
- Lecturas sin estación asociada: 0

Se cargaron correctamente los datos meteorológicos y el catálogo de estaciones. Las 1.351.008 lecturas fueron relacionadas con las 12 estaciones mediante station_id, sin generar registros adicionales ni dejar lecturas sin una estación asociada. Por tanto, se considera cumplido el requisito funcional RF-01.